---
#
# Ansible managed
#
repository:
  description: Install and configure Cisco AnyConnect Secure Mobility Client.
  homepage: https://robertdebock.nl/
  topics: ciscoanyconnect, application, cloud, infrastructure, linux, networking, security, system, tools, ansible, molecule, tox, playbook
